import massive.munit.TestSuite;

// FILE GENERATED BY tools/run_tests.bat, DONT MODIFY BY HAND!
// @@IMPORT
// @@END IMPORT

/**
 * Auto generated Test Suite for MassiveUnit.
 * Refer to munit command line tool for more information (haxelib run munit)
 */

class TestSuite extends massive.munit.TestSuite
{		

	public function new()
	{
		super();

      // @@ADD 
      // @@END ADD
	}
}
