package assets;
import assets.JsonAssets;
import com.firstplayable.hxlib.loader.ResMan;

//WARNING! THIS CLASS IS AUTO-GENERATED BY TOOLS. YOUR CHANGES WILL BE OVERWRITTEN.
class VFXManifest
{
	public static function init():Void
	{
		ResMan.instance.addRes( "VFX", { src : "2d/default_VFX.png" } );
		ResMan.instance.addRes( "VFX", { src : "2d/default_VFX.json", content : JsonAssets._2d_default_VFX } );

		ResMan.instance.addRes( "VFX", { src : "vfx/CollideSticker.json", content : JsonAssets._vfx_CollideSticker } );

	}
}